openapi: 3.0.0
info:
  title: 'Humanity API'
  contact:
    name: Humanity
    url: 'https://www.humanity.com'
    email: support@humanity.com
  version: '0.1'
servers:
  -
    url: 'https://www.humanity.com'
  -
    url: 'https://www.humanity.engineering.com'
paths:
  '/api/v2/integration-api/{vendorType}/employee':
    post:
      tags:
        - Integrations
      summary: 'Create or update employee'
      description: 'Create or update an employee with given integration id'
      operationId: createOrUpdateEmployee
      parameters:
        -
          $ref: '#/components/parameters/vendorType'
        -
          name: integrationId
          in: query
          description: 'Employee id'
          required: true
          schema:
            type: string
            maxLength: 512
            minLength: 1
        -
          name: first_name
          in: query
          description: 'Employee first name'
          required: true
          schema:
            type: string
            maxLength: 50
            minLength: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
              examples:
                'update success':
                  summary: 'update success response'
                  value: { status: 1, data: { id: '50003', eid: null, status: '0', deleted: '0', deleted_by: '0', legal_agree: '0', referral: '0', location: '0', wage: null, name: 'Test_Create_Name Test_Create_LName', nick_name: null, birth_day: '0', birth_month: '0', birth_year: null, email: null, email_confirmed: '0', cell_phone: null, cellphone_confirmed: '0', address: null, city: null, state: null, zip: null, username: 2319370fd2cc163809d957b98c16ad52, realname: 'Test_Update_Name Test_Update_LName', timezone_id: null, daily_overtime: '0', updated_at: '2022-06-01 13:24:46', avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, unique_id: null, job_title: null, gender: null, language: null, employee_type: '0', pay_type: '0', work_start_date: '2022-05-20 12:22:47', home_phone: null, last_visit: '0', registered: '1653049367', smsgateway: null, notes: '', pref_shift_autoconfirm: '-1', undertime: '0', overtime: '-1', max_days_row: '-1', monthly_undertime: '0', monthly_overtime: '-1', pref_mtimebshifts: '0', middle_name: null, registration_ip: 172.18.0.2, vendor_id: 1, signature: null, disp_topics: null, disp_posts: null, email_setting: '1', notify_with_post: '0', auto_notify: '0', show_smilies: '1', show_avatars: '1', show_sig: '1', access_keys: '0', dst: '0', time_format: '0', date_format: '0', style: ShiftPlanning, num_posts: '0', last_post: null, last_search: null, last_email_sent: null, admin_note: null, activate_string: null, activate_key: null, pun_bbcode_enabled: '1', pun_bbcode_use_buttons: '1', pun_pm_new_messages: null, pun_pm_long_subject: '1', newsletter: '1', last_sms_sent: '0', p_email: '1', p_phone: '1', notify_sms: '-1', notify_email: '1', e_new_pm: '0', ical: 'https:\/\/team.humanity.engineering\/ical\/58b0d1f0d42956ae32caa15fa34b7f94.ics', startday: '1', pref_caltime: '10', recommendation: '', tut_v2_sched: '0', screen_logger: '0', sc_freq: '-2', newsletter_receiver: '0', pref_sp_skin: '0', inline_wizard_completion: null, title: null, url: null, recommend: '0', jabber: null, icq: null, msn: null, aim: null, yahoo: null, integration_primary_employee_position_id: null, firstname: Test_Update_Name, lastname: Test_Update_LName, tusername: 2319370fd2cc163809d957b98c16ad52, 24hr: '0', group: '5', last_active: null, timezone: '415', timezone_name: UTC, group_name: Employee, status_name: 'Not Activated', schedules: [], skills: [], custom: [], settings: { widgets_layout: [[timeclock, training, files, upcomingshifts, anniversary, notices], [onnow, leaves, lateforwork, birthdays], [messagewall]], widgets_enabled: [timeclock, training, upcomingshifts, anniversary, onnow, leaves, lateforwork, birthdays, messagewall, files], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1, notifications: { channel_email: 1, channel_sms: 1, channel_mobile_push: 1, email: [], sms: [], mobile_push: [] } }, permissions: { allow_wage_and_budget: true }, saved_filters: null, integrations: { Workato: [{ id: '1003', employee_id: 50003, company_id: '123', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634135, extra: null }] } }, metadata: [], token: b1e43398e00b11ec9d640242ac120002aaf78e14, errors: null }
                'create success':
                  summary: 'create success response'
                  value: { status: 1, data: { id: '50004', eid: null, status: '0', deleted: '0', deleted_by: '0', legal_agree: '0', referral: '0', location: '0', wage: null, name: '', nick_name: null, birth_day: '0', birth_month: '0', birth_year: null, email: null, email_confirmed: '0', cell_phone: null, cellphone_confirmed: '0', address: null, city: null, state: null, zip: null, username: 5757161a2c8d208c75f5ffe78a05ea90, realname: null, timezone_id: null, daily_overtime: '0', updated_at: '2022-06-01 14:30:41', avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, unique_id: null, job_title: null, gender: null, language: null, employee_type: '0', pay_type: '0', work_start_date: '2022-06-01 14:30:41', home_phone: null, last_visit: '0', registered: '1654093841', smsgateway: null, notes: '', pref_shift_autoconfirm: '-1', undertime: '0', overtime: '-1', max_days_row: '-1', monthly_undertime: '0', monthly_overtime: '-1', pref_mtimebshifts: '0', middle_name: null, registration_ip: 172.20.0.5, vendor_id: 11, signature: null, disp_topics: null, disp_posts: null, email_setting: '1', notify_with_post: '0', auto_notify: '0', show_smilies: '1', show_avatars: '1', show_sig: '1', access_keys: '0', dst: '0', time_format: '0', date_format: '0', style: ShiftPlanning, num_posts: '0', last_post: null, last_search: null, last_email_sent: null, admin_note: null, activate_string: null, activate_key: null, pun_bbcode_enabled: '1', pun_bbcode_use_buttons: '1', pun_pm_new_messages: null, pun_pm_long_subject: '1', newsletter: '1', last_sms_sent: '0', p_email: '1', p_phone: '1', notify_sms: '-1', notify_email: '1', e_new_pm: '0', ical: 'https:\/\/team.humanity.engineering\/ical\/db86cdebdcb7c88a714ea0078d3e91aa.ics', startday: '1', pref_caltime: '10', recommendation: '', tut_v2_sched: '0', screen_logger: '0', sc_freq: '-2', newsletter_receiver: '0', pref_sp_skin: '0', inline_wizard_completion: null, title: null, url: null, recommend: '0', jabber: null, icq: null, msn: null, aim: null, yahoo: null, integration_primary_employee_position_id: null, firstname: Create_Name, lastname: Create_LastName, tusername: 5757161a2c8d208c75f5ffe78a05ea90, 24hr: '0', group: '5', last_active: null, timezone: '415', timezone_name: UTC, group_name: Employee, status_name: 'Not Activated', schedules: [], skills: [], custom: [], settings: { widgets_layout: [[timeclock, training, files, upcomingshifts, anniversary, notices], [onnow, leaves, lateforwork, birthdays], [messagewall]], widgets_enabled: [timeclock, training, upcomingshifts, anniversary, onnow, leaves, lateforwork, birthdays, messagewall, files], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1, notifications: { channel_email: 1, channel_sms: 1, channel_mobile_push: 1, email: [], sms: [], mobile_push: [] } }, permissions: { allow_wage_and_budget: true }, saved_filters: null, integrations: { Workato: [{ id: '1004', employee_id: 50004, company_id: '1234', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634142, extra: null }] } }, metadata: [], token: b1e43398e00b11ec9d640242ac120002aaf78e14, errors: null }
                'create error':
                  summary: 'create error response'
                  value: { status: 12, data: 'Create Failed - Your CREATE request failed', errors: 'Employee already exists.', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                'create invalid param error':
                  summary: 'create invalid param error response'
                  value: { status: 9, data: 'Invalid parameters - Your request has an invalid parameter type', errors: 'Supplied data has failed validation', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                'update error':
                  summary: 'update error response'
                  value: { status: 8, data: 'Missing parameters - Your request is missing a required parameter', errors: 'missing: first_name', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                'update permissions error':
                  summary: 'update permissions error response'
                  value: { status: 13, data: 'Update Failed - Your UPDATE request failed', errors: 'You don''t have permission to perform this action', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
        '500':
          $ref: '#/components/responses/500'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
  '/api/v2/integration-api/{vendorType}/employees/{integrationId}':
    get:
      tags:
        - Integrations
      summary: 'Get an employee data'
      description: 'Return employee data for given integration id'
      operationId: getEmployee
      parameters:
        -
          $ref: '#/components/parameters/vendorType'
        -
          $ref: '#/components/parameters/integrationId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
              examples:
                success:
                  summary: 'success response'
                  value: { status: 1, data: { id: '50000', eid: null, status: '0', deleted: '0', deleted_by: '0', legal_agree: '0', referral: '0', location: '0', wage: null, name: 'Test1 Testing1', nick_name: null, birth_day: '0', birth_month: '0', birth_year: null, email: null, email_confirmed: '0', cell_phone: null, cellphone_confirmed: '0', address: null, city: null, state: null, zip: null, username: 8a0eee06f20ef49cb709a6381572e651, realname: 'Test1 Testing1', timezone_id: null, daily_overtime: '0', updated_at: '2022-05-31 09:14:50', avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, unique_id: null, job_title: null, gender: null, language: null, employee_type: '0', pay_type: '0', work_start_date: '2022-05-31 09:14:50', home_phone: null, last_visit: '0', registered: '1653988490', smsgateway: null, notes: '', pref_shift_autoconfirm: '-1', undertime: '0', overtime: '-1', max_days_row: '-1', monthly_undertime: '0', monthly_overtime: '-1', pref_mtimebshifts: '0', middle_name: null, registration_ip: 172.19.0.6, vendor_id: 11, signature: null, disp_topics: null, disp_posts: null, email_setting: '1', notify_with_post: '0', auto_notify: '0', show_smilies: '1', show_avatars: '1', show_sig: '1', access_keys: '0', dst: '0', time_format: '0', date_format: '0', style: ShiftPlanning, num_posts: '0', last_post: null, last_search: null, last_email_sent: null, admin_note: null, activate_string: null, activate_key: null, pun_bbcode_enabled: '1', pun_bbcode_use_buttons: '1', pun_pm_new_messages: null, pun_pm_long_subject: '1', newsletter: '1', last_sms_sent: '0', p_email: '1', p_phone: '1', notify_sms: '-1', notify_email: '1', e_new_pm: '0', ical: 'https:\/\/team.humanity.engineering\/ical\/df76ccc4a5202fcb5a6ecbcde9580472.ics', startday: '1', pref_caltime: '10', recommendation: '', tut_v2_sched: '0', screen_logger: '0', sc_freq: '-2', newsletter_receiver: '0', pref_sp_skin: '0', inline_wizard_completion: null, title: null, url: null, recommend: '0', jabber: null, icq: null, msn: null, aim: null, yahoo: null, integration_primary_employee_position_id: null, firstname: Test1, lastname: Testing1, tusername: 8a0eee06f20ef49cb709a6381572e651, 24hr: '0', group: '5', last_active: null, timezone: '415', timezone_name: UTC, timezone_info: { timezone_id: '415', name: UTC, name_formatted: '(UTC) UTC', offset: '+0:00', seconds: 0, hours: 0, default: '1', minutes: 0 }, group_name: Employee, status_name: 'Not Activated', schedules: [], skills: [], custom: [], settings: { widgets_layout: [], widgets_enabled: [], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1, notifications: { channel_email: 1, channel_sms: 1, channel_mobile_push: 1, email: [], sms: [], mobile_push: [] } }, permissions: { allow_wage_and_budget: true }, saved_filters: null, integrations: { Workato: [{ id: '1000', employee_id: 50000, company_id: '123', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634137, extra: null }] } }, metadata: [], errors: null, token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                error:
                  summary: 'error response'
                  value: { status: 15, data: 'Get Failed - Your GET request failed', errors: 'Unable to find entity where integration_id=152046dee350017fb2cf8a1a0b634137 and integration_type=1234.', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
        '500':
          $ref: '#/components/responses/500'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
    delete:
      tags:
        - Integrations
      summary: 'Delete employee'
      description: 'Delete an employee with given integration id'
      operationId: deleteEmployee
      parameters:
        -
          $ref: '#/components/parameters/vendorType'
        -
          $ref: '#/components/parameters/integrationId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
              examples:
                success:
                  summary: 'success response'
                  value: { status: 1, data: [], metadata: [], token: b1e43398e00b11ec9d640242ac120002aaf78e14, errors: null }
                error:
                  summary: 'error response'
                  value: { status: 14, data: 'Delete Failed - Your DELETE request failed', errors: 'Unable to find entity where integration_id=152046dee350017fb2cf8a1a0b634139 and integration_type=1234.', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
        '500':
          $ref: '#/components/responses/500'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
  '/api/v2/integration-api/{vendorType}/employees/':
    get:
      tags:
        - Integrations
      summary: 'Get all employees'
      description: 'Return data about all employees under the company'
      operationId: getEmployees
      parameters:
        -
          $ref: '#/components/parameters/vendorType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
              examples:
                success:
                  summary: 'success response'
                  value: { status: 1, data: [{ id: '50000', language: null, work_start_date: '2022-05-31 08:53:03', eid: null, name: Test1, firstname: Testing1, lastname: null, username: 8a0eee06f20ef49cb709a6381572e651, email: null, group: '5', status: '0', deleted: '0', wage: null, nick_name: null, birth_day: '0', birth_month: '0', cell_phone: null, home_phone: null, avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, address: null, city: null, state: null, zip: null, notes: '', ical: 'https:\/\/team.humanity.engineering\/ical\/7f8245177d4544ac6787627b2524b54d.ics', registered: '1653987183', p_phone: '1', p_email: '1', location: '0', timezone: '415', job_title: null, updated_at: '2022-05-31 08:53:04', unique_id: null, daily_overtime: '0', vendor_id: 1, schedules: [], skills: [], timezone_name: UTC, group_name: Employee, status_name: 'Not Activated', custom: [], settings: { widgets_layout: [], widgets_enabled: [], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1 }, last_active: null, integrations: { Workato: [{ id: '1000', employee_id: 50000, company_id: '123', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634137, extra: null }] } }, { id: '50001', language: null, work_start_date: '2022-05-31 09:14:50', eid: null, name: 'Test2 Testing2', firstname: Test2, lastname: Testing2, username: 348232c7e8c1f0ad0243dff8b9c8830e, email: null, group: '5', status: '0', deleted: '0', wage: null, nick_name: null, birth_day: '0', birth_month: '0', cell_phone: null, home_phone: null, avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, address: null, city: null, state: null, zip: null, notes: '', ical: 'https:\/\/team.humanity.engineering\/ical\/df76ccc4a5202fcb5a6ecbcde9580472.ics', registered: '1653988490', p_phone: '1', p_email: '1', location: '0', timezone: '415', job_title: null, updated_at: '2022-05-31 09:14:50', unique_id: null, daily_overtime: '0', vendor_id: 11, schedules: [], skills: [], timezone_name: UTC, group_name: Employee, status_name: 'Not Activated', custom: [], settings: { widgets_layout: [], widgets_enabled: [], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1 }, last_active: null, integrations: { Workato: [{ id: '1001', employee_id: 50001, company_id: '123', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634138, extra: null }] } }, { id: '50002', language: null, work_start_date: '2022-05-20 14:31:28', eid: null, name: 'Test0 Testing0', firstname: Test0, lastname: Testing0, username: 3ba2b4b2bba7a52eca84ae358878530c, email: ds+testworkato@email.com, group: '5', status: '0', deleted: '0', wage: null, nick_name: null, birth_day: '0', birth_month: '0', cell_phone: null, home_phone: null, avatar: { small: \/app\/layout\/images\/no_avatar.png, medium: \/app\/layout\/images\/no_avatar.png, large: \/app\/layout\/images\/no_avatar.png }, avatar_url: null, address: null, city: null, state: null, zip: null, notes: '', ical: 'https:\/\/team.humanity.engineering\/ical\/d365599be1fea7ca86f6930eb7ca2eac.ics', registered: '1653057088', p_phone: '1', p_email: '1', location: '0', timezone: '415', job_title: null, updated_at: '2022-05-31 08:52:23', unique_id: null, daily_overtime: '0', vendor_id: 1, schedules: [], skills: [], timezone_name: UTC, group_name: Employee, status_name: 'Not Activated', custom: [], settings: { widgets_layout: [], widgets_enabled: [], schedule_side_panel_visibility: 1, linked_shift_time: 1, schedule_view_selected: week, schedule_timeline_selected: employee, schedule_budget_mode_visibility: 0, schedule_forecast_graph_visibility: 0, forecast_demand_graph_visibility: 0, schedule_copy_rules_choice: 0, shift_skill_filter_visibility: 0, shift_task_assignment_visibility: 0, default_location_panel_visibility: 1, include_ghost_shifts: 0, is_first_schedule_visit: 0, is_new_shift_creation_enabled: 1 }, last_active: null, integrations: { Workato: [{ id: '1002', employee_id: 50002, company_id: '123', integration_type: 1234, integration_id: 152046dee350017fb2cf8a1a0b634136, extra: null }] } }], metadata: [], errors: null, token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                'success empty':
                  summary: 'empty response'
                  value: { status: 1, data: [], metadata: [], errors: null, token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
                error:
                  summary: 'error response'
                  value: { status: 15, data: 'Get Failed - Your GET request failed', errors: 'Error happened while fetching integrations data', token: b1e43398e00b11ec9d640242ac120002aaf78e14 }
        '500':
          $ref: '#/components/responses/500'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
components:
  schemas:
    responseError400:
      properties:
        status:
          type: integer
        data:
          nullable: true
        error:
          type: string
      type: object
    responseError401:
      properties:
        errors:
          type: string
      type: object
    responseError500:
      properties:
        error:
          type: string
      type: object
    ResponseObject:
      properties:
        status:
          type: integer
        metadata:
          type: array
          items:
            type: object
          nullable: true
        data:
          type: object
          oneOf:
            -
              type: object
            -
              type: string
            -
              type: array
              items:
                type: object
              minItems: 1
            -
              nullable: true
        errors:
          type: string
          nullable: true
        token:
          type: string
      type: object
  responses:
    '400':
      description: 'Bad request!'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError400'
          examples:
            error:
              summary: 'Bad request'
              value:
                status: 0
                data: null
                error: 'Resource not found'
    '401':
      description: 'Unauthorized! Access token is missing or invalid.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError401'
          examples:
            error:
              summary: Unauthorized
              value:
                status: 3
                data: 'Invalid token key - Please re-authenticate'
                error: 'Missing API Token.'
                token: null
    '500':
      description: 'Unexpected error occures!'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError500'
          examples:
            error:
              summary: 'Internal Server Error'
              value:
                error: 'syntax error, unexpected token'
  parameters:
    integrationId:
      name: integrationId
      in: path
      description: 'Employee id'
      required: true
      schema:
        type: string
        maxLength: 512
        minLength: 1
    vendorType:
      name: vendorType
      in: path
      description: 'Vendor id'
      required: true
      schema:
        type: integer
        format: base64
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  -
    bearerAuth: []
